// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.3"
	GitCommit   = "84fd105"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-23 07:02" // UTC
)
