// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.0"
	GitCommit   = "e0d074a"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-23 07:01" // UTC
)
