// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.5"
	GitCommit   = "0321532"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-23 15:27" // UTC
)
